# Generated by Django 5.2.5 on 2025-09-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='taken_at',
            new_name='date_taken',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='total',
            new_name='total_questions',
        ),
    ]
